name: CodeLanka
description: Coding to Empower Sri Lanka
meta_description: "About CodeLanka"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://codelanka.github.io'
google_analytics: 'UA-XXXXXXXX-X'

# Details for the RSS feed generator
url:            'blog url'
author:         'codelanka'
